name: Production Deploy

on:
  push:
    branches:
      - master

jobs:
  preview-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          npm install
          VITE_MODE=production npm run build
      - name: Deploy to production
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: lrs-fe
          directory: build
          gitHubToken: ${{ github.token }}
          branch: master
